[build]
  command = "sed -i '' 's|{{ VITE_SUPABASE_URL }}|'$VITE_SUPABASE_URL'|g; s|{{ VITE_SUPABASE_KEY }}|'$VITE_SUPABASE_KEY'|g' index.html"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
